/**
 * Named summits, viewpoints and passes across Nepal, drawn on every trek map
 * as a small dot with a hover card.
 *
 * Coordinates are summit points rounded to 4 decimals (~11 m), each one taken
 * from the matching OpenStreetMap node and cross-checked against Wikidata
 * where the two sources or a published figure disagreed. Do not eyeball a new
 * entry onto the map — look up its node, or the dot lands on a neighbouring
 * slope. Heights stay at the value trekkers see published (which is sometimes
 * a little off the DEM-derived figure in OSM); feet are derived from the metre
 * value, so only edit the metres.
 *
 * `kind` separates true summits from the viewpoints and passes trekkers
 * actually walk to, so the map can style and filter them differently.
 */

export type PeakKind = "peak" | "viewpoint" | "pass";

export interface NepalPeak {
  name: string;
  /** Local or alternative name shown under the title in the hover card. */
  altName?: string;
  lng: number;
  lat: number;
  /** Height above sea level, in metres. */
  elevation: number;
  /** Trekking/climbing region the peak belongs to. */
  region: string;
  kind: PeakKind;
  /** One or two lines of context for the hover card. */
  note?: string;
}

export const NEPAL_PEAKS: NepalPeak[] = [
  // ---------------------------------------------------------------- 8,000 m
  {
    name: "Mount Everest",
    altName: "Sagarmatha / Chomolungma",
    lng: 86.9252,
    lat: 27.9881,
    elevation: 8849,
    region: "Khumbu — Mahalangur Himal",
    kind: "peak",
    note: "The highest point on earth, on the Nepal–Tibet border. First climbed in 1953 by Edmund Hillary and Tenzing Norgay.",
  },
  {
    name: "Kanchenjunga",
    altName: "Kumbhakarna Himal",
    lng: 88.1475,
    lat: 27.703,
    elevation: 8586,
    region: "Kanchenjunga — far east Nepal",
    kind: "peak",
    note: "Third highest mountain in the world. Climbers stop just short of the summit out of respect for the peak's sanctity.",
  },
  {
    name: "Lhotse",
    lng: 86.9325,
    lat: 27.962,
    elevation: 8516,
    region: "Khumbu — Mahalangur Himal",
    kind: "peak",
    note: "Everest's southern neighbour, sharing the same South Col. Fourth highest in the world.",
  },
  {
    name: "Makalu",
    lng: 87.0884,
    lat: 27.8914,
    elevation: 8485,
    region: "Makalu Barun",
    kind: "peak",
    note: "A near-perfect four-sided pyramid, 19 km south-east of Everest. Fifth highest in the world.",
  },
  {
    name: "Cho Oyu",
    lng: 86.6596,
    lat: 28.0967,
    elevation: 8188,
    region: "Khumbu — Gokyo / Nangpa La",
    kind: "peak",
    note: "Sixth highest in the world and widely considered the most accessible 8,000 m peak.",
  },
  {
    name: "Dhaulagiri I",
    lng: 83.4895,
    lat: 28.6976,
    elevation: 8167,
    region: "Dhaulagiri",
    kind: "peak",
    note: "Seventh highest in the world. It rises 7,000 m above the Kali Gandaki gorge directly opposite Annapurna.",
  },
  {
    name: "Manaslu",
    altName: "Kutang",
    lng: 84.5597,
    lat: 28.55,
    elevation: 8163,
    region: "Manaslu",
    kind: "peak",
    note: "Eighth highest in the world and the centrepiece of the Manaslu Circuit.",
  },
  {
    name: "Annapurna I",
    lng: 83.8199,
    lat: 28.5958,
    elevation: 8091,
    region: "Annapurna",
    kind: "peak",
    note: "The first 8,000 m peak ever climbed, by Maurice Herzog's French team in 1950.",
  },

  // ---------------------------------------------------------------- 7,000 m
  {
    name: "Gyachung Kang",
    lng: 86.7448,
    lat: 28.098,
    elevation: 7952,
    region: "Khumbu — Mahalangur Himal",
    kind: "peak",
    note: "The highest mountain in the world below 8,000 m, between Everest and Cho Oyu.",
  },
  {
    name: "Annapurna II",
    lng: 84.1218,
    lat: 28.535,
    elevation: 7937,
    region: "Annapurna",
    kind: "peak",
    note: "The eastern anchor of the Annapurna range, seen for days from the Marsyangdi valley.",
  },
  {
    name: "Himalchuli",
    lng: 84.6367,
    lat: 28.4377,
    elevation: 7893,
    region: "Manaslu",
    kind: "peak",
  },
  {
    name: "Ngadi Chuli",
    altName: "Peak 29",
    lng: 84.5672,
    lat: 28.5039,
    elevation: 7871,
    region: "Manaslu",
    kind: "peak",
  },
  {
    name: "Nuptse",
    lng: 86.887,
    lat: 27.9674,
    elevation: 7861,
    region: "Khumbu — Mahalangur Himal",
    kind: "peak",
    note: "The wall that hides Everest from Base Camp; its name means 'west peak'.",
  },
  {
    name: "Dhaulagiri II",
    lng: 83.3874,
    lat: 28.7632,
    elevation: 7751,
    region: "Dhaulagiri",
    kind: "peak",
  },
  {
    name: "Kumbhakarna",
    altName: "Jannu",
    lng: 88.044,
    lat: 27.684,
    elevation: 7710,
    region: "Kanchenjunga",
    kind: "peak",
    note: "A sheer granite fortress west of Kanchenjunga, one of the hardest walls in the Himalaya.",
  },
  {
    name: "Annapurna Fang",
    altName: "Baraha Shikhar",
    lng: 83.8007,
    lat: 28.5783,
    elevation: 7647,
    region: "Annapurna",
    kind: "peak",
  },
  {
    name: "Annapurna III",
    lng: 83.9891,
    lat: 28.5854,
    elevation: 7555,
    region: "Annapurna",
    kind: "peak",
  },
  {
    name: "Annapurna IV",
    lng: 84.0836,
    lat: 28.5369,
    elevation: 7525,
    region: "Annapurna",
    kind: "peak",
  },
  {
    name: "Khangsar Kang",
    altName: "Roc Noir",
    lng: 83.8629,
    lat: 28.6108,
    elevation: 7485,
    region: "Annapurna — Tilicho",
    kind: "peak",
  },
  {
    name: "Gangapurna",
    lng: 83.9635,
    lat: 28.6057,
    elevation: 7455,
    region: "Annapurna",
    kind: "peak",
    note: "Rises straight out of the glacial lake above Manang.",
  },
  {
    name: "Ganesh Himal I",
    altName: "Yangra",
    lng: 85.127,
    lat: 28.3917,
    elevation: 7422,
    region: "Ganesh Himal",
    kind: "peak",
  },
  {
    name: "Kabru",
    altName: "Kabru North",
    lng: 88.1183,
    lat: 27.635,
    elevation: 7412,
    region: "Kanchenjunga",
    kind: "peak",
  },
  {
    name: "Churen Himal",
    lng: 83.2101,
    lat: 28.7316,
    elevation: 7371,
    region: "Dhaulagiri",
    kind: "peak",
  },
  {
    name: "Kirat Chuli",
    altName: "Tent Peak",
    lng: 88.1971,
    lat: 27.7915,
    elevation: 7365,
    region: "Kanchenjunga",
    kind: "peak",
  },
  {
    name: "Nangpai Gosum I",
    altName: "Pasang Lhamu Chuli",
    lng: 86.6127,
    lat: 28.0731,
    elevation: 7351,
    region: "Khumbu — Nangpa La",
    kind: "peak",
  },
  {
    name: "Chamlang",
    lng: 86.9811,
    lat: 27.777,
    elevation: 7319,
    region: "Makalu Barun",
    kind: "peak",
  },
  {
    name: "Putha Hiunchuli",
    lng: 83.1454,
    lat: 28.7479,
    elevation: 7246,
    region: "Dhaulagiri — Dolpo",
    kind: "peak",
  },
  {
    name: "Langtang Lirung",
    lng: 85.5167,
    lat: 28.2564,
    elevation: 7227,
    region: "Langtang",
    kind: "peak",
    note: "The giant above Kyanjin Gompa and the highest peak in the Langtang valley.",
  },
  {
    name: "Annapurna South",
    lng: 83.8063,
    lat: 28.5184,
    elevation: 7219,
    region: "Annapurna",
    kind: "peak",
    note: "The wall on the left as you walk into Annapurna Base Camp.",
  },
  {
    name: "Langtang Ri",
    lng: 85.6839,
    lat: 28.3824,
    elevation: 7205,
    region: "Langtang",
    kind: "peak",
  },
  {
    name: "Gurja Himal",
    lng: 83.2757,
    lat: 28.6741,
    elevation: 7193,
    region: "Dhaulagiri",
    kind: "peak",
  },
  {
    name: "Pumori",
    lng: 86.8274,
    lat: 28.0159,
    elevation: 7161,
    region: "Khumbu — Everest Base Camp",
    kind: "peak",
    note: "'Unmarried daughter' — the pyramid directly above Everest Base Camp and Kala Patthar.",
  },
  {
    name: "Gaurishankar",
    lng: 86.3345,
    lat: 27.9674,
    elevation: 7134,
    region: "Rolwaling",
    kind: "peak",
    note: "Sacred to both Hindus and Buddhists; its twin summits are named for Shiva and Parvati.",
  },
  {
    name: "Tilicho Peak",
    lng: 83.8115,
    lat: 28.6829,
    elevation: 7134,
    region: "Annapurna — Tilicho",
    kind: "peak",
    note: "Stands over Tilicho Lake, one of the highest large lakes in the world.",
  },
  {
    name: "Api",
    lng: 80.9292,
    lat: 30.0058,
    elevation: 7132,
    region: "Far West — Api Nampa",
    kind: "peak",
    note: "The highest peak in far-western Nepal, rarely seen by trekkers.",
  },
  {
    name: "Baruntse",
    lng: 86.9796,
    lat: 27.8721,
    elevation: 7129,
    region: "Makalu Barun",
    kind: "peak",
  },
  {
    name: "Himlung Himal",
    lng: 84.4221,
    lat: 28.7719,
    elevation: 7126,
    region: "Nar Phu — Manaslu",
    kind: "peak",
  },
  {
    name: "Nilgiri North",
    lng: 83.7444,
    lat: 28.6898,
    elevation: 7061,
    region: "Annapurna — Kali Gandaki",
    kind: "peak",
  },
  {
    name: "Saipal",
    lng: 81.495,
    lat: 29.8908,
    elevation: 7031,
    region: "Far West — Humla / Bajhang",
    kind: "peak",
  },

  // ---------------------------------------------------------------- 6,000 m
  {
    name: "Machhapuchhre",
    altName: "Fishtail",
    lng: 83.9492,
    lat: 28.495,
    elevation: 6993,
    region: "Annapurna — Pokhara skyline",
    kind: "peak",
    note: "Sacred to Shiva and closed to climbing. The twin summit only looks like a fish tail from the east.",
  },
  {
    name: "Lamjung Himal",
    lng: 84.1886,
    lat: 28.4895,
    elevation: 6983,
    region: "Annapurna",
    kind: "peak",
  },
  {
    name: "Dorje Lakpa",
    lng: 85.7786,
    lat: 28.1754,
    elevation: 6966,
    region: "Langtang — Jugal Himal",
    kind: "peak",
  },
  {
    name: "Numbur",
    altName: "Numberchuli / Shorong Yul Lha",
    lng: 86.5726,
    lat: 27.7542,
    elevation: 6959,
    region: "Solu — Rolwaling",
    kind: "peak",
  },
  {
    name: "Tukuche Peak",
    lng: 83.5574,
    lat: 28.745,
    elevation: 6920,
    region: "Dhaulagiri",
    kind: "peak",
  },
  {
    name: "Kanjiroba",
    lng: 82.6379,
    lat: 29.376,
    elevation: 6883,
    region: "Dolpo",
    kind: "peak",
    note: "The high point of the remote Dolpo region, above Shey Phoksundo.",
  },
  {
    name: "Nilgiri South",
    lng: 83.7296,
    lat: 28.6541,
    elevation: 6839,
    region: "Annapurna — Kali Gandaki",
    kind: "peak",
  },
  {
    name: "Ama Dablam",
    lng: 86.8604,
    lat: 27.8621,
    elevation: 6812,
    region: "Khumbu",
    kind: "peak",
    note: "'Mother's necklace' — the most photographed peak on the Everest Base Camp trail.",
  },
  {
    name: "Kangtega",
    lng: 86.8175,
    lat: 27.793,
    elevation: 6782,
    region: "Khumbu",
    kind: "peak",
    note: "The 'snow saddle' above Namche and Tengboche.",
  },
  {
    name: "Nampa",
    lng: 80.9936,
    lat: 30.0059,
    elevation: 6755,
    region: "Far West — Api Nampa",
    kind: "peak",
  },
  {
    name: "Baudha Peak",
    altName: "Bhauda Himal",
    lng: 84.6768,
    lat: 28.3762,
    elevation: 6672,
    region: "Manaslu",
    kind: "peak",
  },
  {
    name: "Thamserku",
    lng: 86.7852,
    lat: 27.79,
    elevation: 6623,
    region: "Khumbu",
    kind: "peak",
    note: "The fluted wall that towers over Namche Bazaar.",
  },
  {
    name: "Chulu East",
    lng: 84.0347,
    lat: 28.7361,
    elevation: 6584,
    region: "Annapurna — Manang",
    kind: "peak",
  },
  {
    name: "Taboche",
    lng: 86.7794,
    lat: 27.8973,
    elevation: 6542,
    region: "Khumbu",
    kind: "peak",
  },
  {
    name: "Mera Peak",
    lng: 86.8687,
    lat: 27.7098,
    elevation: 6476,
    region: "Hinku — Makalu Barun",
    kind: "peak",
    note: "Nepal's highest trekking peak; five 8,000 m summits are visible from the top.",
  },
  {
    name: "Hiunchuli",
    lng: 83.85,
    lat: 28.51,
    elevation: 6441,
    region: "Annapurna Sanctuary",
    kind: "peak",
    note: "Guards the right-hand side of the gateway into the Annapurna Sanctuary.",
  },
  {
    name: "Cholatse",
    lng: 86.7652,
    lat: 27.9196,
    elevation: 6440,
    region: "Khumbu — Cho La",
    kind: "peak",
  },
  {
    name: "Chulu West",
    lng: 84.0228,
    lat: 28.7454,
    elevation: 6419,
    region: "Annapurna — Manang",
    kind: "peak",
  },
  {
    name: "Kusum Kanguru",
    lng: 86.7893,
    lat: 27.7309,
    elevation: 6367,
    region: "Khumbu",
    kind: "peak",
    note: "The hardest of Nepal's trekking peaks despite its modest height.",
  },
  {
    name: "Saribung",
    lng: 84.1719,
    lat: 28.885,
    elevation: 6346,
    region: "Upper Mustang — Damodar Himal",
    kind: "peak",
  },
  {
    name: "Island Peak",
    altName: "Imja Tse",
    lng: 86.9346,
    lat: 27.92,
    elevation: 6189,
    region: "Khumbu — Chhukung",
    kind: "peak",
    note: "The most-climbed trekking peak in the Everest region, named for the way it sits in the Imja glacier.",
  },
  {
    name: "Kongde Ri",
    lng: 86.6428,
    lat: 27.793,
    elevation: 6187,
    region: "Khumbu",
    kind: "peak",
  },
  {
    name: "Lobuche East",
    lng: 86.7917,
    lat: 27.9594,
    elevation: 6119,
    region: "Khumbu — Everest Base Camp",
    kind: "peak",
  },
  {
    name: "Pisang Peak",
    lng: 84.1881,
    lat: 28.6487,
    elevation: 6091,
    region: "Annapurna — Manang",
    kind: "peak",
  },
  {
    name: "Dhampus Peak",
    altName: "Thapa Peak",
    lng: 83.6064,
    lat: 28.798,
    elevation: 6012,
    region: "Dhaulagiri — Hidden Valley",
    kind: "peak",
  },
  {
    name: "Naya Kanga",
    lng: 85.5484,
    lat: 28.1686,
    elevation: 5844,
    region: "Langtang",
    kind: "peak",
  },
  {
    name: "Mardi Himal",
    lng: 83.9275,
    lat: 28.4738,
    elevation: 5587,
    region: "Annapurna — Mardi Himal",
    kind: "peak",
    note: "The small summit behind Machhapuchhre that gives the Mardi Himal trek its name.",
  },
  {
    name: "Yala Peak",
    lng: 85.622,
    lat: 28.2409,
    elevation: 5520,
    region: "Langtang",
    kind: "peak",
    note: "A straightforward first Himalayan summit above Kyanjin Gompa.",
  },

  // ------------------------------------------------------- viewpoints & passes
  {
    name: "Kala Patthar",
    lng: 86.8284,
    lat: 27.9958,
    elevation: 5644,
    region: "Khumbu — Everest Base Camp",
    kind: "viewpoint",
    note: "The classic sunrise viewpoint for Everest's south face, above Gorak Shep.",
  },
  {
    name: "Kongma La",
    lng: 86.8362,
    lat: 27.9297,
    elevation: 5535,
    region: "Khumbu — Three Passes",
    kind: "pass",
  },
  {
    name: "Cho La",
    lng: 86.7516,
    lat: 27.9617,
    elevation: 5420,
    region: "Khumbu — Three Passes",
    kind: "pass",
    note: "Glaciated crossing between Gokyo and the Everest Base Camp trail.",
  },
  {
    name: "Thorong La",
    lng: 83.9388,
    lat: 28.7935,
    elevation: 5416,
    region: "Annapurna Circuit",
    kind: "pass",
    note: "The high point of the Annapurna Circuit, crossed from Manang to Muktinath.",
  },
  {
    name: "Renjo La",
    lng: 86.6585,
    lat: 27.9474,
    elevation: 5360,
    region: "Khumbu — Three Passes",
    kind: "pass",
  },
  {
    name: "Gokyo Ri",
    lng: 86.6831,
    lat: 27.9615,
    elevation: 5357,
    region: "Khumbu — Gokyo",
    kind: "viewpoint",
    note: "Looks over the Gokyo lakes to Everest, Lhotse, Makalu and Cho Oyu at once.",
  },
  {
    name: "Larke La",
    lng: 84.5203,
    lat: 28.6639,
    elevation: 5106,
    region: "Manaslu Circuit",
    kind: "pass",
    note: "The one big pass on the Manaslu Circuit.",
  },
  {
    name: "Tserko Ri",
    lng: 85.6005,
    lat: 28.2132,
    elevation: 4984,
    region: "Langtang",
    kind: "viewpoint",
    note: "The day-hike viewpoint above Kyanjin Gompa.",
  },
  {
    name: "Mardi Himal Viewpoint",
    lng: 83.889,
    lat: 28.4578,
    elevation: 4500,
    region: "Annapurna — Mardi Himal",
    kind: "viewpoint",
    note: "The end of the Mardi Himal ridge, face to face with Machhapuchhre.",
  },
  {
    name: "Pikey Peak",
    lng: 86.4728,
    lat: 27.5325,
    elevation: 4065,
    region: "Solu — Lower Everest",
    kind: "viewpoint",
    note: "Tenzing Norgay's favourite view of Everest, on the low-altitude Pikey Peak trek.",
  },
  {
    name: "Poon Hill",
    lng: 83.6895,
    lat: 28.4,
    elevation: 3210,
    region: "Annapurna — Ghorepani",
    kind: "viewpoint",
    note: "Nepal's best-known sunrise viewpoint, over Dhaulagiri and Annapurna South.",
  },
];

const METRES_TO_FEET = 3.28084;

/** "8,849 m" — the label drawn next to the dot once the map is zoomed in. */
function metresLabel(elevation: number) {
  return `${elevation.toLocaleString("en-US")} m`;
}

export interface PeakFeatureProperties {
  name: string;
  altName: string;
  elevation: number;
  elevationFt: number;
  elevationLabel: string;
  region: string;
  kind: PeakKind;
  note: string;
  lng: number;
  lat: number;
}

/**
 * The same list as a GeoJSON FeatureCollection, ready to hand to a maplibre
 * `geojson` source. Every property the hover card needs is inlined so the
 * popup can be built straight from the queried feature.
 */
export const NEPAL_PEAKS_GEOJSON = {
  type: "FeatureCollection" as const,
  features: NEPAL_PEAKS.map((peak) => ({
    type: "Feature" as const,
    geometry: { type: "Point" as const, coordinates: [peak.lng, peak.lat] },
    properties: {
      name: peak.name,
      altName: peak.altName ?? "",
      elevation: peak.elevation,
      elevationFt: Math.round(peak.elevation * METRES_TO_FEET),
      elevationLabel: metresLabel(peak.elevation),
      region: peak.region,
      kind: peak.kind,
      note: peak.note ?? "",
      lng: peak.lng,
      lat: peak.lat,
    } satisfies PeakFeatureProperties,
  })),
};
