/**
 * Working list for the package-coverage blog build: which of the packages
 * without a primary article get their own guide, and which are route or
 * logistics variants of a package that already has one.
 */
export const VARIANTS: Record<string, string> = {
  // Annapurna Base Camp route variants
  "abc-trek-nepal": "annapurna-base-camp-trek",
  "annapurna-base-camp-trek-from-pokhara": "annapurna-base-camp-trek",
  "annapurna-base-camp-with-ghorepani-poonhill-from-pokhara": "annapurna-base-camp-trek",
  "annapurna-base-camp-trek-with-ghorepani-poonhill-trek": "annapurna-base-camp-trek",
  "annapurna-base-camp-trek-with-mardi-himal-trek-from-pokhara": "annapurna-base-camp-trek",
  "mardi-himal-trek-with-annapurna-base-camp": "annapurna-base-camp-trek",
  "annapurna-circuit-with-tilicho-lake-trek": "annapurna-circuit-trek",
  "short-annapurna-circuit-trek": "annapurna-circuit-trek",
  "short-tilicho-lake-trek": "tilicho-lake-trek",
  "jomsom-muktinath-trek-from-pokhara": "jomsom-muktinath-trek",
  "khopra-danda-trek-from-pokhara": "khopra-danda-trek",
  "khori-himal-trek-from-pokhara": "khori-himal-trek",
  "lower-mustang-trek-from-pokhara": "lower-mustang-trek",
  "mohare-danda-trek-from-pokhara": "mohare-danda-trek",
  "upper-mustang-trek-from-pokhara": "upper-mustang-trek",
  "everest-base-camp-trek-with-gokyo-lakes-and-cho-la-pass": "everest-base-camp-trek",
  "langtang-gosaikunda-lake-trek": "langtang-valley-trek",
  "larke-pass-trek": "manaslu-circuit-trek",
  "tsum-valley-and-manaslu-circuit-trek": "manaslu-circuit-trek",
  "tashi-lapcha-pass-trek": "rolwaling-valley-trek",
  // Climbing combinations and logistics variants
  "ama-dablam-expedition-and-island-peak-climbing": "ama-dablam-expedition",
  "ama-dablam-expedition-with-helicopter-return": "ama-dablam-expedition",
  "short-ama-dablam-expedition": "ama-dablam-expedition",
  "baruntse-expedition-with-mera-peak-climbing": "baruntse-expedition",
  "everest-and-lhotse-expedition": "everest-expedition",
  "island-peak-climbing-from-chhukung": "island-peak-climbing",
  "island-peak-climbing-with-helicopter-return": "island-peak-climbing",
  "island-mera-peak-climbing-with-gokyo-ebc": "island-peak-climbing",
  "lobuche-peak-and-island-peak-climbing": "island-peak-climbing",
  "mera-and-island-peak-climbing": "mera-peak-climbing",
  "mera-island-and-lobuche-peak-climbing": "mera-peak-climbing",
  "mera-peak-amphu-lapcha": "mera-peak-climbing",
  "short-mera-peak-climbing": "mera-peak-climbing",
  "makalu-base-camp-with-sherpani-col-and-mera-peak-climbing": "makalu-base-camp-trek",
  "pachermo-and-kyajo-ri-peak-climbing": "pachermo-peak-climbing",
  "yalung-ri-and-pachermo-peak-climbing": "pachermo-peak-climbing",
  "pokalde-island-and-lobuche-climbing": "pokalde-peak-climbing",
  "three-peaks-climbing-island-lobuche-kyajo-ri": "island-peak-climbing",
  "tharpu-chuli-and-singu-chuli-two-peaks-climbing": "singu-chuli-peak-climbing",
  // Tours and activities already covered by a topic guide
  "bardia-jungle-safari-tour-5-days": "bardia-national-park-tour-4-days",
  "2-night-3-days-bardia-tour": "bardia-national-park-tour-4-days",
  "chitwan-national-park-tour-4-days": "chitwan-national-park-tour-3-days",
  "1-night-2-days-chitwan-trip": "chitwan-national-park-tour-3-days",
  "bird-watching-in-chitwan-national-park": "koshi-tappu-wildlife-reserve-tour",
  "bird-watching-in-kathmandu-valley": "koshi-tappu-wildlife-reserve-tour",
  "bird-watching-in-pokhara-lakes": "koshi-tappu-wildlife-reserve-tour",
  "cross-country-paragliding-in-pokhara": "paragliding-in-pokhara",
  "mountain-flight-from-pokhara": "everest-mountain-flight",
  "zip-flyer-in-kushma": "bungee-jump-in-kushma",
  "bungee-jumping-in-pokhara": "bungee-jump-in-kushma",
  "zipline-in-pokhara-zip-flyer": "bungee-jump-in-kushma",
  "gosainkunda-holy-tour": "gosaikunda-lake-trek",
  "muktinath-helicopter-tour-from-pokhara": "muktinath-pilgrimage-tour",
  "pokhara-day-tour-with-sarangkot-sunrise": "pokhara-day-tour",
  "glimpse-of-nepal-tour": "kathmandu-pokhara-tour",
  "trishuli-river-rafting-1-day": "trishuli-river-rafting-2-days",
  // Everest helicopter shuttle segments — all one subject
  "gorakshep-to-kathmandu-helicopter-flight": "everest-base-camp-helicopter-tour",
  "gorakshep-to-lukla-helicopter-flight": "everest-base-camp-helicopter-tour",
  "kalapatthar-to-kathmandu-helicopter-flight": "everest-base-camp-helicopter-tour",
  "kathmandu-to-lukla-helicopter-flight": "everest-base-camp-helicopter-tour",
  "lukla-to-kathmandu-helicopter-flight": "everest-base-camp-helicopter-tour",
  "namche-to-kathmandu-helicopter-flight": "everest-base-camp-helicopter-tour",
};
