import { AIRPORT, AIRPORT_PLACE, KATHMANDU, KTM_PLACE, KTM_RETURN_PLACE, p, type NewTrek } from "./types";

/** Gokyo lakes, Gokyo Ri, the Cho La and Everest Base Camp in one circuit. */
export const ebcGokyoChoLaTrek: NewTrek = {
  region: "Everest Region",
  price: 1690,
  difficulty: "difficult",
  maxAltitude: 5545,
  center: [86.76, 27.92],
  zoom: 10.2,
  content: {
    slug: "everest-base-camp-trek-with-gokyo-lakes-and-cho-la-pass",
    title: "Everest Base Camp Trek with Gokyo Lakes and Cho La Pass",
    overview:
      "<p>The <strong>Everest Base Camp Trek with Gokyo Lakes and Cho La Pass</strong> links the two finest viewpoints in the Khumbu into a single circuit. It climbs the quiet Gokyo valley to the turquoise lakes and <strong>Gokyo Ri (5,357 m)</strong>, crosses the glaciated <strong>Cho La (5,420 m)</strong> into the Khumbu valley, then continues to <strong>Everest Base Camp (5,364 m)</strong> and <strong>Kala Patthar (5,545 m)</strong> before walking out the classic way.</p><p>It is a considerably better trip than the base camp trail alone. Gokyo Ri gives a wider panorama than Kala Patthar — four 8,000 m peaks in one view, with the <strong>Ngozumpa Glacier</strong>, the longest in Nepal, filling the valley below — and the first half of the route sees a fraction of the traffic. The Cho La in the middle is what makes it difficult: a genuine high pass with a short glacier crossing and an early start, and the reason this itinerary asks for more fitness and a longer holiday than the standard trek.</p>",
    highlights: [
      ["Gokyo Ri (5,357 m)", "The best single panorama in the Khumbu: Everest, Lhotse, Makalu and Cho Oyu from one summit."],
      ["The Gokyo Lakes", "A chain of six turquoise glacial lakes at 4,700 m to 5,000 m, beside the longest glacier in Nepal."],
      ["Cho La Pass (5,420 m)", "A genuine glaciated crossing linking the Gokyo and Khumbu valleys, and the crux of the trek."],
      ["Everest Base Camp and Kala Patthar", "The foot of the Khumbu Icefall, and the classic dawn view of Everest's south-west face."],
      ["Two Valleys, One Trek", "The quiet Gokyo side on the way up and the classic Khumbu trail on the way down, with no backtracking."],
    ],
    sections: [
      {
        heading: "Best Time to Trek",
        content:
          "<p><strong>Mid-March to May</strong> and <strong>late September to mid-November</strong>. The Cho La narrows the window compared with the standard base camp trek, because the pass holds snow and ice and becomes genuinely serious outside those months. Autumn is the more reliable of the two for the crossing: the air is clearest, the ice is firm and the route is well trodden.</p><p>Spring is warmer and brings rhododendron below Namche, but the pass can carry fresh snow into April and occasionally needs a fixed line. We avoid the <strong>monsoon</strong> entirely — the Cho La is a bad place in poor visibility — and do not run this route in <strong>winter</strong>, when the pass is frequently impassable and the Gokyo lodges largely close. If your dates are fixed in winter, the standard base camp trek is the right alternative.</p>",
      },
      {
        heading: "Trek Difficulty & Fitness",
        content:
          "<p>This is a difficult trek, a clear step above the standard base camp route. You spend seven nights above 4,300 m, climb two peaks over 5,300 m, and cross a glaciated pass at <strong>5,420 m</strong>. The Cho La day is the hardest of the trip: a 3 a.m. start, a steep scramble up loose rock to the pass, a short crossing of a crevassed glacier where your guide will rope the group if conditions require it, and a long descent to Dzongla — ten to twelve hours on the move.</p><p>You should be a confident hill walker with previous multi-day trekking experience and, ideally, some time above 4,000 m. Three months of structured preparation is realistic: long hill days with a loaded pack, plus running or cycling for the aerobic base. Microspikes and an ice axe are not needed in normal conditions, but the crew carries a rope and basic hardware for the pass.</p>",
      },
      {
        heading: "Travel Insurance",
        content:
          "<p>Travel insurance covering <strong>trekking to 6,000 m</strong> is mandatory, and the policy must explicitly permit crossing a glaciated pass. Some insurers class the Cho La as mountaineering rather than trekking; read the wording and, if in doubt, buy the mountaineering upgrade. A rejected claim at 5,400 m is not a good place to discover the difference.</p><p><strong>Emergency helicopter evacuation, medical treatment and repatriation</strong> must all be covered. There is no road anywhere on this route and the only way off the Cho La is on foot or by air. Also look for <strong>flight delay and cancellation</strong> cover for the Lukla sector. Send us your policy number and the insurer's 24-hour emergency line before departure — we will not start the trek without it.</p>",
      },
      {
        heading: "Packing List",
        content:
          "<p>Everything on the standard base camp list plus a margin for the pass. Waterproof trekking boots with a stiff sole and good ankle support, three or four base layers, a fleece, a <strong>down jacket rated to -20°C</strong>, and a genuinely waterproof shell jacket and trousers. Add thermal leggings, a warm hat, sun hat, liner gloves and insulated gloves, gaiters for the Cho La, and five pairs of wool socks. A sleeping bag rated to <strong>-20°C</strong> is right for Gokyo and Gorak Shep.</p><p>Also pack a 35-litre daypack, trekking poles, a headlamp with spare batteries for the pre-dawn pass start, category 4 sunglasses and a spare pair, high-SPF sunscreen and lip balm, a reusable bottle plus an insulated flask, purification tablets or a filter, a first aid kit with blister care and rehydration salts, and a power bank. <strong>Microspikes</strong> are worth carrying in spring. Keep the duffel under 10 kg for Lukla.</p>",
      },
      {
        heading: "Accommodation, Food & Drinking Water",
        content:
          "<p>Teahouse lodges throughout, but the standard varies more than on the classic trail. Namche, Phakding and Lukla are comfortable, several with attached bathrooms. The Gokyo valley lodges at <strong>Dole</strong>, <strong>Machhermo</strong> and <strong>Gokyo</strong> are simpler and fewer, and <strong>Dragnag</strong> and <strong>Dzongla</strong> on either side of the pass have only a handful of beds each — which is exactly why this itinerary books ahead and why we run fixed departures rather than taking walk-ins.</p><p>Three meals a day are included on the trek. Menus are the standard Khumbu range of <em>dal bhat</em>, fried rice, noodles, soup, potatoes, pasta and eggs, thinner at Dragnag and Dzongla than elsewhere. Go vegetarian above Namche. Drinking water comes from lodge taps and boiled supplies; treat it with tablets, a filter or a UV pen, and carry an insulated flask because bottles freeze overnight above Gokyo.</p>",
      },
    ],
    faqs: [
      { question: "How hard is the Cho La really?", answer: "It is the hardest day on any teahouse trek in the Khumbu. Expect a 3 a.m. start, two to three hours of steep loose rock and a short scramble to the notch, a glacier crossing of perhaps 45 minutes where the crew may rope you together, then a long rubbly descent. Ten to twelve hours. Fit trekkers manage it comfortably; unfit ones have a miserable day." },
      { question: "Do I need mountaineering experience or technical gear?", answer: "No experience is needed and no technical gear is required of you. The crew carries a rope, harnesses and basic hardware in case conditions demand them. Microspikes are useful in spring and can be hired in Namche. If the pass is genuinely out of condition, we reverse the route via Phortse rather than force it." },
      { question: "Which is the better viewpoint, Gokyo Ri or Kala Patthar?", answer: "Gokyo Ri, by most reckonings, and this trek gives you both. Gokyo Ri shows four 8,000 m peaks — Everest, Lhotse, Makalu and Cho Oyu — with the Ngozumpa Glacier below. Kala Patthar is closer to Everest and shows the south-west face and the icefall better. They are different views rather than competing ones." },
      { question: "Can the itinerary be walked in the other direction?", answer: "Yes, and we sometimes do. Going Everest Base Camp first and crossing the Cho La westward into Gokyo means you are better acclimatised on the pass. The drawback is a harder descent on the Gokyo side, which is steeper. Your guide decides on the ground based on the group and the snow." },
      { question: "What happens if someone cannot cross the pass?", answer: "There is a walk-out from Gokyo down the valley and across to Phortse and Namche that avoids the Cho La entirely, adding a day. If one person is struggling, an assistant guide takes them that way and the group meets again at Namche. This is one reason we run a second guide on this itinerary." },
      { question: "Is there a fifth and sixth lake beyond Gokyo?", answer: "Yes. The fourth and fifth lakes are a two to four hour walk north along the Ngozumpa moraine, and Scoundrel's Viewpoint above the fifth gives a spectacular Everest panorama. It is an option on the Gokyo acclimatisation day for people going well, in place of a second Gokyo Ri climb." },
      { question: "How many nights are spent above 4,000 m?", answer: "Nine, from Dole onward. That is the reason the itinerary includes acclimatisation days at Namche and Gokyo and does not rush the Gokyo valley. Your guide checks oxygen saturation every evening from Dole and will hold the group or descend if the numbers say to." },
      { question: "Are the Gokyo lodges as good as the ones on the main trail?", answer: "Not quite, but they are better than they used to be. Gokyo itself has several solid lodges with heated dining rooms and hot showers. Dole and Machhermo are simpler. Dragnag has two lodges and Dzongla three, both very basic, which is normal for settlements that exist only for the pass." },
      { question: "Can we see Everest from Gokyo village itself?", answer: "Not from the village — the ridge blocks it. You need Gokyo Ri, which is a steep 700 m climb of two to three hours above the lake, or the walk to the fifth lake. Both are on the itinerary in one form or another, and the dawn climb of Gokyo Ri is the one people remember." },
      { question: "How much cash should I carry for this route?", answer: "More than on the standard trek, because the Gokyo side charges more for everything and there is no ATM after Namche. Budget $25 to $35 a day for drinks, snacks, charging, showers and Wi-Fi, plus tips at the end. Draw rupees in Kathmandu and top up in Namche on the way through." },
    ],
    inclusions: {
      flights: ["Round-trip domestic flight from Kathmandu to Lukla and back."],
      transport: ["Private airport and hotel transfers in Kathmandu."],
      cityAccommodation: ["Two nights of accommodation in Kathmandu with breakfast."],
      permits: "Sagarmatha National Park entry permit and the Khumbu Pasang Lhamu Rural Municipality permit.",
      extra: [
        "An assistant guide for the Cho La crossing, with rope and basic glacier hardware carried by the crew.",
        "Daily oxygen saturation monitoring with a pulse oximeter carried by the guide.",
      ],
    },
    exclusions: {
      cityMeals: "Lunch and dinner in Kathmandu.",
      extra: ["Microspikes and gaiters, which can be hired in Kathmandu or Namche."],
      unforeseen:
        "Any additional accommodation, transportation, or expenses caused by weather closing the Cho La, Lukla flight delays, or other circumstances beyond the itinerary.",
    },
    porterDays: 14,
    fixedDepartureDay: "sunday",
    itineraryDescription:
      "A 17-day Khumbu circuit up the quiet Gokyo valley to Gokyo Ri, over the Cho La at 5,420 m, and on to Everest Base Camp and Kala Patthar.",
    inExDescription:
      "Airport transfers, Lukla flights, Kathmandu hotel nights, teahouse accommodation, all trekking meals, national park and municipality permits, a licensed guide and an assistant guide for the pass, trekking map, first aid, and government taxes are included, while international flights, visa, insurance, personal gear, porter service, city meals, personal expenses, and tips are excluded.",
    bestTime: "Mar-May, Sep-Nov",
    meta: {
      title: "Everest Base Camp Trek with Gokyo Lakes and Cho La Pass – 17 Days",
      description:
        "A 17-day Khumbu circuit taking in the Gokyo lakes, Gokyo Ri, the Cho La pass at 5,420 m, Everest Base Camp and Kala Patthar, with no backtracking.",
      keywords:
        "Everest Base Camp trek via Gokyo, Cho La pass trek, Gokyo lakes trek, Gokyo Ri, EBC Gokyo Cho La, Everest base camp Gokyo lakes trek, Ngozumpa glacier",
      tags: "Everest Base Camp Trek with Gokyo Lakes and Cho La Pass, Everest Region, Gokyo, Cho La, High Pass Trek, Nepal Trekking",
    },
  },
  days: [
    {
      title: "Arrival in Nepal – Kathmandu (1,400 m)",
      elevation: "1,400 m",
      accommodation: "Kathmandu",
      placeDescription: KTM_PLACE,
      ...KATHMANDU,
      html: p(
        "Welcome to Nepal. You land at <strong>Tribhuvan International Airport</strong> in <strong>Kathmandu (1,400 m)</strong>, where our representative meets you in the arrivals hall and drives you to your hotel in Thamel.",
        "Your guide joins you in the afternoon for the briefing, which on this itinerary is a longer conversation than usual. We go through the acclimatisation plan for the Gokyo valley, what the Cho La day involves, and the conditions under which we would reverse the route or send someone round via Phortse.",
        "We check your kit carefully — the pass needs a proper shell, gaiters and warm gloves, and anything missing can be bought or hired a few streets away. Duffels must come in under 10 kg for the Lukla flight. Overnight in Kathmandu.",
      ),
    },
    {
      title: "Fly to Lukla (2,840 m) and Trek to Phakding (2,610 m)",
      elevation: "2,610 m",
      accommodation: "Phakding",
      placeDescription: "A riverside village on the Dudh Koshi, the first night's stop on the walk in from Lukla.",
      lng: 86.71235560127043,
      lat: 27.73968542596356,
      html: p(
        "An early transfer to the domestic terminal for the flight to <strong>Lukla (2,840 m)</strong>. In peak season the sector runs from Ramechhap rather than Kathmandu, in which case we drive overnight and fly at dawn; your guide confirms which applies to your departure.",
        "The 35-minute flight runs east along the Himalayan wall before the short uphill landing at Tenzing-Hillary Airport.",
        "After tea while the porters sort loads, you start walking. The trail drops gently through Chheplung and Ghat, crossing and re-crossing the <strong>Dudh Koshi</strong> on suspension bridges strung with prayer flags, past mani walls and carved stones.",
        "Around 3 to 4 hours of easy walking to <strong>Phakding (2,610 m)</strong>, a deliberately short first day that keeps the sleeping altitude low. Overnight in a teahouse.",
      ),
    },
    {
      title: "Trek from Phakding (2,610 m) to Namche Bazaar (3,440 m)",
      elevation: "3,440 m",
      accommodation: "Namche Bazaar",
      placeDescription: "The Sherpa capital of the Khumbu, a horseshoe of lodges and shops above the Dudh Koshi confluence.",
      lng: 86.71031,
      lat: 27.80344,
      html: p(
        "The first substantial day. The trail follows the Dudh Koshi upstream through <strong>Monjo (2,835 m)</strong>, where you enter <strong>Sagarmatha National Park</strong> and permits are checked, then drops to the river and crosses the high <strong>Hillary Suspension Bridge</strong> above the confluence with the Bhote Koshi.",
        "From there it climbs steeply for two hours through pine forest. Roughly halfway up a gap in the trees gives the first view of <strong>Everest (8,848 m)</strong> over the Nuptse-Lhotse wall.",
        "The climb finishes at <strong>Namche Bazaar (3,440 m)</strong>, built in a natural amphitheatre and stacked with lodges, bakeries and gear shops. Saturday is market day, when traders come up from the lowlands and over from Tibet.",
        "Around 6 hours with 830 m of ascent. Overnight in a teahouse at Namche.",
      ),
    },
    {
      title: "Acclimatisation Day at Namche Bazaar (3,440 m)",
      elevation: "3,440 m",
      accommodation: "Namche Bazaar",
      placeDescription: "The Sherpa capital of the Khumbu, a horseshoe of lodges and shops above the Dudh Koshi confluence.",
      lng: 86.71031,
      lat: 27.80344,
      html: p(
        "An active rest day: climb high, sleep low.",
        "The morning walk goes up to the <strong>Everest View Hotel</strong> at 3,880 m, an hour and a half of steady climbing, where the terrace looks straight up the valley at Everest, Lhotse, Nuptse and <strong>Ama Dablam (6,812 m)</strong>.",
        "The loop returns through <strong>Khumjung</strong> and <strong>Khunde</strong>, the two large Sherpa villages on the shelf behind Namche, past the monastery that keeps a purported yeti scalp and the hospital Edmund Hillary's trust built in 1966. It is a good introduction to the valley you spend the next fortnight in.",
        "The afternoon is free for the bakeries, the Sherpa Culture Museum, or hiring gaiters and microspikes for the pass. Overnight in Namche.",
      ),
    },
    {
      title: "Trek from Namche Bazaar (3,440 m) to Dole (4,200 m)",
      elevation: "4,200 m",
      accommodation: "Dole",
      placeDescription: "A small cluster of lodges in a side valley on the way up to Gokyo, above the treeline.",
      lng: 86.6883,
      lat: 27.8714,
      html: p(
        "Today you leave the base camp trail. The path contours north out of Namche on the same balcony as the classic route, then at <strong>Sanasa</strong> takes the left fork that almost nobody else is walking.",
        "The trail climbs through <strong>Mong La (3,975 m)</strong>, a saddle with a chorten and a tea shop and a wide view back down the Dudh Koshi, then drops steeply 400 m to the river at <strong>Phortse Thanga (3,680 m)</strong>.",
        "The afternoon is a sustained climb through rhododendron and birch that thins as you go, with waterfalls on the valley wall and Khumbila overhead, to the handful of lodges at <strong>Dole (4,200 m)</strong>. The treeline is behind you by the time you arrive.",
        "Around 5 to 6 hours. Overnight in a teahouse at Dole.",
      ),
    },
    {
      title: "Trek from Dole (4,200 m) to Machhermo (4,470 m)",
      elevation: "4,470 m",
      accommodation: "Machhermo",
      placeDescription: "A summer grazing settlement in a broad side valley beneath Kangtega and Thamserku.",
      lng: 86.6961,
      lat: 27.9153,
      html: p(
        "A short, deliberately gentle day — only 270 m of net gain — because the Gokyo valley gains height quickly and this is where acclimatisation is won or lost.",
        "The trail climbs steadily above the Dudh Koshi through scrub juniper and dwarf rhododendron, passing the summer settlements of <strong>Lhabarma</strong> and <strong>Luza</strong>, small clusters of stone huts used for yak grazing.",
        "The valley is wide and open here, with <strong>Cho Oyu (8,188 m)</strong> beginning to show at the head of it and Kangtega and Thamserku behind you.",
        "You reach <strong>Machhermo (4,470 m)</strong> by early afternoon. The Himalayan Rescue Association runs an aid post here and gives a free altitude sickness talk most afternoons in season, which is genuinely worth attending.",
        "Around 4 to 5 hours. Overnight in a teahouse at Machhermo.",
      ),
    },
    {
      title: "Trek from Machhermo (4,470 m) to Gokyo (4,790 m)",
      elevation: "4,790 m",
      accommodation: "Gokyo",
      placeDescription: "A lodge settlement on the shore of the third Gokyo lake, beside the Ngozumpa Glacier.",
      lng: 86.69361609738701,
      lat: 27.953896435081496,
      html: p(
        "A spectacular morning. The trail climbs to a ridge above Machhermo with a first sight of the terminal moraine of the <strong>Ngozumpa Glacier</strong>, the longest glacier in Nepal, then descends to the river at Phangga and climbs steeply onto the moraine wall itself.",
        "From there you pass the lakes in turn: the <strong>first lake, Longpongo (4,690 m)</strong>, where mani stones line the shore; the <strong>second, Taboche Tsho</strong>, an improbable turquoise against the grey moraine; and finally the <strong>third, Dudh Pokhari</strong>, on whose eastern shore the lodges of <strong>Gokyo (4,790 m)</strong> stand.",
        "The colour of the water is the thing people remember — a mineral blue-green that looks artificial in photographs and is not.",
        "Around 4 to 5 hours. Overnight in a teahouse at Gokyo.",
      ),
    },
    {
      title: "Acclimatisation Day at Gokyo (4,790 m) – Gokyo Ri (5,357 m)",
      elevation: "5,357 m",
      accommodation: "Gokyo",
      placeDescription: "A lodge settlement on the shore of the third Gokyo lake, beside the Ngozumpa Glacier.",
      lng: 86.69361609738701,
      lat: 27.953896435081496,
      html: p(
        "The best viewpoint in the Khumbu, climbed at dawn. <strong>Gokyo Ri (5,357 m)</strong> rises directly behind the lodges: a steep, unrelenting 570 m of zigzags on scree and rock that takes two to three hours in the cold and dark.",
        "The summit is worth every step. From the prayer flags you look across the Ngozumpa Glacier at four of the world's six highest mountains — <strong>Everest (8,848 m)</strong>, <strong>Lhotse (8,516 m)</strong>, <strong>Makalu (8,485 m)</strong> and <strong>Cho Oyu (8,188 m)</strong> — with the lakes far below and Ama Dablam and Kangtega to the south.",
        "Back at the lodge for a late breakfast. Groups going well can walk north along the moraine to the <strong>fourth and fifth lakes</strong> and <strong>Scoundrel's Viewpoint</strong> in the afternoon; everyone else rests, which is equally useful before the pass.",
        "Overnight in Gokyo.",
      ),
    },
    {
      title: "Trek from Gokyo (4,790 m) to Dragnag (4,700 m)",
      elevation: "4,700 m",
      accommodation: "Dragnag",
      placeDescription: "Two lodges on the eastern side of the Ngozumpa Glacier, the staging point for the Cho La.",
      lng: 86.7239,
      lat: 27.9367,
      html: p(
        "A short day whose only purpose is to put you on the right side of the glacier for the pass.",
        "The route crosses the <strong>Ngozumpa Glacier</strong> itself — an hour and a half to two hours over a chaotic surface of rubble-covered ice, with meltwater pools, unstable moraine and a marked but shifting path. Your guide leads the line and the crossing is done in the morning while the surface is frozen and stable.",
        "On the far side a short climb brings you to <strong>Dragnag (4,700 m)</strong>, sometimes written Thagnak: two lodges and a yak shed against the hillside, and nothing else.",
        "You arrive by early afternoon. The rest of the day is spent resting, eating and sorting kit, because tomorrow starts in the dark. Your guide runs through the pass plan after dinner. Overnight in a teahouse at Dragnag.",
      ),
    },
    {
      title: "Cross the Cho La (5,420 m) and Trek to Dzongla (4,830 m)",
      elevation: "5,420 m",
      accommodation: "Dzongla",
      placeDescription: "A tiny lodge settlement on a shelf below the Cho La, looking across at Ama Dablam.",
      lng: 86.77358643766156,
      lat: 27.93950539783947,
      html: p(
        "The hardest and best day of the trek, starting around 3 a.m. by headlamp so that you are over the pass before the afternoon wind and cloud arrive.",
        "The trail climbs gradually up a boulder-strewn valley, then steepens into a rough scramble on loose rock and scree to the notch of the <strong>Cho La (5,420 m)</strong>. Hands come out of pockets on the last section.",
        "The pass itself is a corniced saddle hung with prayer flags. Beyond it comes a short crossing of a <strong>crevassed glacier</strong> — 30 to 45 minutes on firm morning ice, where the crew will rope the group if conditions call for it — followed by a long, knee-punishing descent over moraine.",
        "Ahead the whole time is <strong>Ama Dablam (6,812 m)</strong>, and the day ends at the three lodges of <strong>Dzongla (4,830 m)</strong> on a grassy shelf above the valley. Ten to twelve hours. Overnight at Dzongla.",
      ),
    },
    {
      title: "Trek from Dzongla (4,830 m) to Lobuche (4,940 m)",
      elevation: "4,940 m",
      accommodation: "Lobuche",
      placeDescription: "A small cluster of lodges on the lateral moraine of the Khumbu Glacier.",
      lng: 86.8097,
      lat: 27.9494,
      html: p(
        "A short, easy and very welcome day after the pass.",
        "The trail contours east across open hillside above the <strong>Chola Tsho</strong> and <strong>Tshola Tsho</strong> lakes, gaining almost no height, with Cholatse and Taboche rising directly on your left and Ama Dablam behind.",
        "It joins the main Everest Base Camp trail just above the <strong>Thukla Pass (4,830 m)</strong>, where the memorial chortens stand for climbers lost on Everest — a sobering, windswept place that most people spend some time in.",
        "From the junction it is a level walk along the moraine to <strong>Lobuche (4,940 m)</strong>, a handful of lodges under the Nuptse wall. You will notice the difference in traffic immediately: this is the busy trail again.",
        "Around 3 to 4 hours. Overnight in a teahouse at Lobuche.",
      ),
    },
    {
      title: "Trek to Everest Base Camp (5,364 m) and Return to Gorak Shep (5,164 m)",
      elevation: "5,364 m",
      accommodation: "Gorak Shep",
      placeDescription: "The last settlement before Everest Base Camp, on a sandy flat beside the Khumbu Glacier.",
      lng: 86.82976404191841,
      lat: 27.981443484744254,
      html: p(
        "The day the trek is named for. A rough two to three hour trail follows the lateral moraine of the Khumbu Glacier north, undulating over loose rock and sand, to the frozen lakebed and lodges of <strong>Gorak Shep (5,164 m)</strong>.",
        "After an early lunch and dropping your bags you continue to <strong>Everest Base Camp (5,364 m)</strong>, two hours each way across boulder fields and glacier debris marked with cairns and prayer flags.",
        "In spring the camp is a small tented town beneath the <strong>Khumbu Icefall</strong>, with expedition teams moving through their rotations; outside the season it is bare ice and moraine and quieter for it.",
        "Standing at the foot of the icefall, with Everest itself hidden directly above and Nuptse walling the valley, is the point of the walk.",
        "Around 8 hours on the move. Overnight at Gorak Shep, the coldest night of the trek.",
      ),
    },
    {
      title: "Kala Patthar (5,545 m) and Trek to Pheriche (4,240 m)",
      elevation: "5,545 m",
      accommodation: "Pheriche",
      placeDescription: "A windswept valley-floor village with the Himalayan Rescue Association aid post.",
      lng: 86.8194,
      lat: 27.8944,
      html: p(
        "A pre-dawn start in the cold for <strong>Kala Patthar (5,545 m)</strong>, the highest point of the trek. It is a steep, slow 90 minutes to two hours up the brown hill above Gorak Shep, and at that altitude every step is deliberate.",
        "From the prayer flags on the summit the whole south-west face of <strong>Everest</strong> stands clear above the Khumbu Icefall, with Nuptse, Lhotse, Pumori and Changtse around you and the glacier winding away below. Sunrise on the summit pyramid is the photograph people come for.",
        "Back to Gorak Shep for breakfast, then the long descent begins. The trail retraces the moraine to Lobuche and drops over the Thukla Pass into the valley, reaching the wide, windy flats at <strong>Pheriche (4,240 m)</strong>.",
        "The oxygen at 4,240 m feels like a different planet after four nights above 4,700 m. Around 8 hours in total. Overnight at Pheriche.",
      ),
    },
    {
      title: "Trek from Pheriche (4,240 m) to Namche Bazaar (3,440 m)",
      elevation: "3,440 m",
      accommodation: "Namche Bazaar",
      placeDescription: "The Sherpa capital of the Khumbu, a horseshoe of lodges and shops above the Dudh Koshi confluence.",
      lng: 86.71031,
      lat: 27.80344,
      html: p(
        "A long but straightforward descent that returns you to the treeline and to comfort.",
        "The trail drops down the Imja valley past <strong>Pangboche</strong>, where the old gompa is worth the short climb into the upper village, then crosses the Imja Khola and climbs briefly to <strong>Tengboche (3,860 m)</strong>. If the timing works, the monastery is worth another visit on the way through.",
        "From Tengboche the path plunges 600 m through rhododendron forest to the river at <strong>Phunki Tenga</strong> — hard on the knees, and where trekking poles earn their place — before the last climb back onto the balcony trail and the level contour into <strong>Namche Bazaar (3,440 m)</strong>.",
        "Around 7 hours. There is a hot shower, a bakery and a beer waiting. Overnight in Namche.",
      ),
    },
    {
      title: "Trek from Namche Bazaar (3,440 m) to Lukla (2,840 m)",
      elevation: "2,840 m",
      accommodation: "Lukla",
      placeDescription: "The Khumbu's gateway town, built around the airstrip that serves the Everest region.",
      lng: 86.73199,
      lat: 27.68707,
      html: p(
        "The last walking day, and a long one, retracing the route down to the airstrip.",
        "The trail drops steeply out of Namche to the <strong>Hillary Suspension Bridge</strong>, then follows the Dudh Koshi downstream through Jorsale and <strong>Monjo</strong>, where you check out of Sagarmatha National Park.",
        "From there it is the gentle riverside walk through Phakding and Ghat, over a succession of suspension bridges, with the final short climb to <strong>Lukla (2,840 m)</strong> at the end — the one uphill nobody expects on the last day.",
        "Around 7 to 8 hours. The evening in Lukla is traditionally the crew party: the guides and porters who carried the trip get their tips and everyone eats and drinks rather more than they have for a fortnight. Overnight in Lukla.",
      ),
    },
    {
      title: "Fly from Lukla (2,840 m) to Kathmandu (1,400 m)",
      elevation: "1,400 m",
      accommodation: "Kathmandu",
      placeDescription: KTM_RETURN_PLACE,
      ...KATHMANDU,
      html: p(
        "An early flight out, because Lukla flies in the morning and grounds when the wind gets up.",
        "The 35-minute hop back over the foothills gives one last look at the Himalayan wall you have spent a fortnight underneath. In peak season the flight lands at Ramechhap and a vehicle brings you the rest of the way to Kathmandu, which adds four to five hours to the day.",
        "Transfer to your hotel, where a hot shower and a room with a heater are the immediate priorities.",
        "The afternoon is free. Thamel is five minutes' walk for souvenirs, and most groups meet for a farewell dinner in the evening. If the Lukla flight is delayed by weather, this is the buffer day it eats — which is why we keep it in the itinerary. Overnight in Kathmandu.",
      ),
    },
    {
      title: "Departure from Nepal",
      elevation: "1,400 m",
      accommodation: "Airport",
      placeDescription: AIRPORT_PLACE,
      ...AIRPORT,
      html: p(
        "A slow morning in Kathmandu. If your flight is late in the day there is time for last shopping in Thamel, a walk around Durbar Square, or a long breakfast, which after seventeen days of lodge food tends to win.",
        "Our representative collects you from the hotel and drives you to <strong>Tribhuvan International Airport</strong> around three hours before departure.",
        "If you are staying on in Nepal we are happy to arrange onward travel, a Chitwan extension, a Pokhara flight or extra hotel nights — tell us while you are still on the trail so we can book it.",
        "Thank you for trekking with us. Crossing the Cho La is a real mountain day and not everyone who sets out on it gets over; we hope to see you back in the Khumbu.",
      ),
    },
  ],
};
