import { p, type TrekDays } from "./types";

/** Upper Dolpo — Phoksundo, the Kang La, Shey Gompa, Saldang and the Tarap valley. */
export const upperDolpoTreks: TrekDays[] = [
  {
    slug: "upper-dolpo-trek",
    days: [
      {
        index: 0,
        title: "Arrival in Kathmandu (1,400 m)",
        html: p(
          "You arrive at Tribhuvan International Airport in <strong>Kathmandu (1,400 m)</strong> and are met by our representative for the transfer to your hotel.",
          "Your guide runs the pre-trek briefing. <strong>Upper Dolpo</strong> is the most remote trekking region in Nepal and among the most culturally intact Tibetan areas anywhere outside Tibet. This 26-day route crosses several passes above 5,000 m, including the <strong>Kang La (5,360 m)</strong>, and visits <strong>Shey Gompa</strong> — the Crystal Monastery — beneath the sacred Crystal Mountain.",
          "It is a restricted area with an expensive special permit, requiring a registered agency and a licensed guide, and it is a full <strong>camping expedition</strong>: there are no lodges on the high sections, so tents, food, kitchen and pack animals go with you.",
          "This is a serious undertaking with sustained time above 4,000 m. Your guide checks equipment carefully — a four-season sleeping bag is essential.",
          "The rest of the day is free. Overnight in Kathmandu.",
        ),
      },
      {
        index: 1,
        title: "Fly from Kathmandu (1,400 m) to Nepalgunj (150 m)",
        html: p(
          "A short flight west to the Terai plains, staging for the mountain flight tomorrow.",
          "The hour-long flight crosses the middle hills and descends over the flat agricultural plain of the <strong>Terai</strong>. On a clear day the Himalaya runs along the whole northern horizon — Ganesh Himal, Manaslu, Annapurna and Dhaulagiri, behind which Dolpo lies in deep rain shadow.",
          "<strong>Nepalgunj (150 m)</strong> is a hot, humid border city close to India, and the change from Kathmandu is abrupt. It is the aviation hub for all of western Nepal and the only practical way into Dolpo.",
          "The afternoon is free. If the heat allows, the <strong>Bageshwori Temple</strong> is worth seeing, and the bazaar has a distinctly Indian character.",
          "Flights to Juphal go at first light and are weather-dependent, so it is an early night. Overnight in Nepalgunj.",
        ),
      },
      {
        index: 2,
        title: "Fly from Nepalgunj (150 m) to Juphal (2,320 m) and Trek to Dunai (2,140 m)",
        html: p(
          "A dramatic mountain flight followed by an easy first walk.",
          "The 45-minute flight to <strong>Juphal (2,320 m)</strong> climbs from the plains over ridge after ridge of the western hills, with the Dhaulagiri massif ahead. The airstrip is a short shelf cut into a hillside. Flights leave early because the wind rises later, and delays are routine.",
          "The crew and pack animals meet you at Juphal, and the walking begins with a gentle descent through terraced fields and pine to the <strong>Thuli Bheri</strong> river, then upstream along the bank.",
          "This is the easiest walking of the whole trek and a useful way to start moving at altitude.",
          "<strong>Dunai (2,140 m)</strong> is the administrative headquarters of Dolpa district — a small town along the riverbank with a checkpoint, shops and a hospital, and the last place with any real services.",
          "Around 2–3 hours. Overnight camping at Dunai.",
        ),
      },
      {
        index: 3,
        title: "Trek from Dunai (2,140 m) to Ankhe (2,896 m)",
        html: p(
          "A climb of around 750 m as the route turns north into the Phoksundo valley.",
          "The trail leaves Dunai and follows the <strong>Thuli Bheri</strong> briefly before turning north up the <strong>Suli Gad</strong> river toward Phoksundo. The valley narrows quickly into a gorge and the path climbs along the wall above the water, crossing side streams and suspension bridges.",
          "The country here is still relatively green — pine, walnut and terraced barley on the lower slopes — but it thins as you climb and the gorge steepens. There are sections where the trail is cut into the rock or built out on wooden galleries.",
          "You enter <strong>Shey Phoksundo National Park</strong>, the largest national park in Nepal, on this stage. Permits are checked at the entrance post.",
          "<strong>Ankhe (2,896 m)</strong> is a small settlement in the gorge. Around 6 hours. Overnight camping at Ankhe.",
        ),
      },
      {
        index: 4,
        title: "Trek from Ankhe (2,896 m) to Sulighat (3,180 m)",
        html: p(
          "A rugged day in the gorge with modest net gain but constant climbing and descending.",
          "The net figure of around 280 m badly understates the day. The trail repeatedly climbs high above the <strong>Suli Gad</strong> to get around cliffs, then drops back to the river, and the cumulative ascent is several times the net gain.",
          "The walking is through forest of pine, birch and walnut on steep valley sides, with the river running fast below. Some sections are narrow and exposed, requiring steady footing, and landslide damage is common in this terrain.",
          "This is good wildlife country within the national park — <strong>blue sheep</strong> on the crags, Himalayan tahr, and excellent birdlife including the Himalayan monal.",
          "<strong>Sulighat (3,180 m)</strong> sits where the valley begins to open toward the Phoksundo basin, and the first views of the peaks around the lake appear.",
          "Around 6 hours. Overnight camping at Sulighat.",
        ),
      },
      {
        index: 5,
        title: "Trek from Sulighat (3,180 m) to Phoksundo Lake (3,612 m)",
        html: p(
          "A climb of around 430 m to the lake — one of the great arrivals of any Nepali trek.",
          "The trail climbs steadily through birch and blue pine, and partway up passes the <strong>Phoksundo waterfall</strong>, at around 167 m the highest in Nepal, where the lake's outflow drops sheer into the gorge. The path switchbacks steeply beside it.",
          "Above the falls the gradient eases and the trail rounds a shoulder, and <strong>Phoksundo Lake (3,612 m)</strong> comes into view: an intense turquoise, held in a steep bowl ringed by cliffs and pine, with no fish and almost no aquatic vegetation. The colour comes from suspended glacial rock flour.",
          "<strong>Ringmo</strong>, the village on the shore, is a traditional Tibetan-style settlement of flat-roofed stone houses with chortens and mani walls, and the <strong>Bön</strong> monastery of Thashung Gompa, around 900 years old, sits nearby.",
          "Around 4–5 hours. Overnight camping at Phoksundo Lake.",
        ),
      },
      {
        index: 6,
        title: "Explore Phoksundo Lake (3,612 m)",
        html: p(
          "A rest and acclimatisation day at 3,612 m in an extraordinary setting.",
          "This is the first proper rest of the trek and an important one — the Kang La at 5,360 m is four days away. The recommended approach is light activity rather than complete rest: the trail along the western shore climbs to a viewpoint over the whole lake and is well worth a couple of hours.",
          "<strong>Ringmo</strong> village is the other focus of the day. Its <strong>Thashung Gompa</strong> belongs to the <strong>Bön</strong> tradition — the pre-Buddhist religion of Tibet, which survives in Dolpo more strongly than almost anywhere. Bön practitioners circumambulate anticlockwise, the reverse of Buddhist custom, which is easy to spot at the chortens.",
          "Parts of the film <em>Himalaya</em> (Caravan) were shot here, and the village is much as it appears in it.",
          "It is also a good day to wash, dry kit and eat well. Overnight camping at Phoksundo Lake.",
        ),
      },
      {
        index: 7,
        title: "Trek from Phoksundo Lake (3,612 m) to Phoksundo Khola (3,507 m)",
        html: p(
          "A short day, but one containing the most famous piece of trail in Dolpo.",
          "The route follows the western shore of the lake, and the first section is the notorious <strong>ledge path</strong> — a narrow trail built from stone and wooden stakes, cut and pinned into a near-vertical cliff face several hundred metres above the water. It appears in <em>Himalaya</em> and it is every bit as airy as it looks.",
          "It is not technically difficult and it is walked by loaded pack animals daily, but it demands full attention and a steady head. Your guide will space the group and let the animals pass.",
          "Beyond the cliff the trail descends to the head of the lake and crosses a broad, flat alluvial plain — a striking change of scale after the ledge — before following the <strong>Phoksundo Khola</strong> upstream.",
          "Camp is beside the river at <strong>3,507 m</strong>. Around 4–5 hours. Overnight camping at Phoksundo Khola.",
        ),
      },
      {
        index: 8,
        title: "Trek from Phoksundo Khola (3,507 m) to Phoksundo Bhanjyang (3,910 m)",
        html: p(
          "A steady climb of around 400 m up an increasingly barren valley toward the pass.",
          "The trail follows the <strong>Phoksundo Khola</strong> north through a narrowing valley, crossing the river on log bridges. The last of the birch and juniper is left behind during the morning, and by the afternoon the landscape is entirely bare — rock, scree and hardy alpine grass.",
          "Progress is unhurried by design. You will cross the <strong>Kang La (5,360 m)</strong> tomorrow, so the pace today is set to arrive at camp with as much in reserve as possible.",
          "The valley walls close in and the peaks at the head come into view. There are no settlements on this stretch and no shelter of any kind; everything is carried by the crew and the pack animals.",
          "<strong>Phoksundo Bhanjyang (3,910 m)</strong> is an exposed camp at the foot of the pass. It is cold, and sleep is often broken at this height.",
          "Around 4–5 hours. Overnight camping at Phoksundo Bhanjyang.",
        ),
      },
      {
        index: 9,
        title: "Trek from Phoksundo Bhanjyang (3,910 m) to Shey Gompa (4,500 m) via Kang La Pass (5,360 m)",
        html: p(
          "The first great pass of the trek — the <strong>Kang La (5,360 m)</strong> — and the arrival at Shey Gompa.",
          "An early start. The climb gains around 1,450 m over bare scree and rock, with no shelter and no water, and at this altitude it is slow, sustained work. It takes most people four to five hours to the top.",
          "The <strong>Kang La</strong> is marked with cairns and prayer flags, and the view is vast: the ranges of Upper Dolpo folding away north toward Tibet, entirely brown and grey and empty, with snow peaks along the horizon.",
          "The descent drops steeply into the Shey valley, following a river down through a gorge.",
          "<strong>Shey Gompa (4,500 m)</strong> — the <strong>Crystal Monastery</strong> — is the spiritual centre of Dolpo, an 11th-century foundation beneath the sacred <strong>Crystal Mountain</strong>, which pilgrims circumambulate. It is the place Peter Matthiessen was travelling to in <em>The Snow Leopard</em>.",
          "A long 7–8 hours. Overnight camping at Shey Gompa.",
        ),
      },
      {
        index: 10,
        title: "Rest Day at Shey Gompa (4,500 m)",
        html: p(
          "A rest and acclimatisation day at 4,500 m at the spiritual heart of Dolpo.",
          "After the Kang La this is a needed break, and there is a great deal to see without going far.",
          "<strong>Shey Gompa</strong>, the Crystal Monastery, dates to the 11th century and belongs to the Kagyu school. Its red buildings and chorten sit beneath <strong>Crystal Mountain</strong> — <em>Shelri</em> — a peak of quartz-veined rock regarded as sacred and circumambulated by pilgrims, particularly during the summer festival. The full <em>kora</em> around the mountain takes a day and is a serious walk at this altitude; a shorter section can be done instead.",
          "<strong>Tsakang Gompa</strong>, a meditation retreat built into a cliff face nearby, is also worth the walk.",
          "This region is prime <strong>snow leopard</strong> habitat, and blue sheep — their main prey — are commonly seen on the slopes.",
          "Overnight camping at Shey Gompa.",
        ),
      },
      {
        index: 11,
        title: "Trek from Shey Gompa (4,500 m) to Namduna Gaun (4,400 m)",
        html: p(
          "A high traverse over the <strong>Saldang La (5,010 m)</strong> with little net height change.",
          "The day looks flat on paper — a loss of 100 m — but it involves a full 500 m climb to the pass and an equivalent descent, all above 4,400 m.",
          "The trail climbs from Shey through a barren valley of rock and scree to the <strong>Saldang La</strong>, marked with cairns and prayer flags. The views from the top run north toward the Tibetan border and back over the Crystal Mountain massif.",
          "The descent leads into a wide, dry valley. This is classic Upper Dolpo terrain: no trees, almost no vegetation, enormous horizontal scale, and colours running from ochre to grey to deep red in the rock bands.",
          "<strong>Namduna Gaun (4,400 m)</strong> is a small settlement with the <strong>Namgung Gompa</strong>, a red monastery built into a cliff face above the village — a striking sight in such empty country.",
          "Around 6 hours. Overnight camping at Namduna Gaun.",
        ),
      },
      {
        index: 12,
        title: "Trek from Namduna Gaun (4,400 m) to Saldang (3,903 m)",
        html: p(
          "A descent of around 500 m to the largest village in Upper Dolpo.",
          "The trail descends through arid, open country, following the valley south-east. The walking is straightforward and the day relatively short, which after several hard stages is welcome.",
          "<strong>Saldang (3,903 m)</strong> is the biggest settlement in Upper Dolpo, strung out for over a kilometre along a terraced hillside above the river. It has several hundred residents in a series of linked hamlets, with barley and buckwheat fields irrigated by channels from the snowmelt.",
          "The culture is entirely Tibetan — the language, the flat-roofed mud-brick architecture, the chortens and mani walls, and the Buddhist and Bön monasteries in and around the village. Saldang sits on an old <strong>trans-Himalayan trading route</strong>, and salt, wool and grain still move north and south across the border here.",
          "It is a good place to spend an afternoon watching ordinary life. Around 4–5 hours. Overnight camping at Saldang.",
        ),
      },
      {
        index: 13,
        title: "Trek from Saldang (3,903 m) to Yangze Gompa (4,960 m)",
        html: p(
          "A substantial climb of around 1,050 m into the far north of Dolpo.",
          "The trail leaves Saldang and climbs steadily north through completely barren country. This is one of the biggest single ascents of the trek, and at these altitudes it is slow going, but you are well acclimatised by this stage.",
          "The landscape is severe and beautiful — bare rock and scree in bands of red, ochre and grey, deeply eroded, with no vegetation beyond lichen and the toughest cushion plants. Blue sheep are frequently seen and Himalayan griffons ride the thermals overhead.",
          "You are close to the Tibetan border here, and the sense of remoteness is complete. Settlements are tiny and far apart.",
          "<strong>Yangze Gompa (4,960 m)</strong> is an old <strong>Bön</strong> monastery in an extremely isolated setting. Bön predates Buddhism in Tibet and survives in Dolpo more strongly than anywhere else in Nepal.",
          "Around 6 hours. Overnight camping at Yangze Gompa.",
        ),
      },
      {
        index: 14,
        title: "Trek from Yangze Gompa (4,960 m) to Sibu (3,942 m)",
        html: p(
          "A long descent of around 1,000 m, turning south toward the Tarap valley.",
          "The trail drops steadily from Yangze, retracing part of the way toward Saldang before turning south down the valley of the <strong>Nagon Khola</strong>. It is a long day but almost entirely downhill, and after the previous stage it feels manageable.",
          "The route passes through small settlements and a series of chortens and mani walls, and there is more evidence of habitation here than in the far north — irrigated fields, grazing yaks, and herders on the trail.",
          "As you lose height, thin scrub and juniper begin to appear again, the first vegetation of any substance in several days, and the temperature rises noticeably.",
          "<strong>Sibu (3,942 m)</strong> is a small settlement of a few houses beside the river, used as a staging point for the Jeng La crossing ahead.",
          "Around 6 hours. Overnight camping at Sibu.",
        ),
      },
      {
        index: 15,
        title: "Trek from Sibu (3,942 m) to Jeng La Phedi (4,845 m)",
        html: p(
          "A climb of around 900 m to the camp beneath the Jeng La.",
          "The trail follows the river upstream before turning up a side valley and climbing steadily toward the pass. The gain is substantial, but the terrain is straightforward and the route is clear.",
          "The vegetation gives out again quickly as you climb, and by the afternoon you are back in the bare rock-and-scree landscape that characterises the high country here. The valley is broad, and the peaks around the head of it come progressively into view.",
          "You may share the trail with yak caravans on this stage — the Tarap valley has long-standing trading links north, and animals are still the only way to move goods in this region.",
          "<strong>Jeng La Phedi (4,845 m)</strong> — <em>phedi</em> means foot of the hill — is an exposed camp with no shelter, positioned for an early start on the pass tomorrow.",
          "Around 5 hours. Overnight camping at Jeng La Phedi.",
        ),
      },
      {
        index: 16,
        title: "Trek from Jeng La Phedi (4,845 m) to Tokyu Gaon (4,240 m) via Jeng La Pass (5,090 m)",
        html: p(
          "The last high pass of the trek — the <strong>Jeng La (5,090 m)</strong> — and the descent into the Tarap valley.",
          "The climb from Phedi is relatively short at around 250 m, and after the Kang La and Saldang La it is the most straightforward of the three. An early start is still sensible, as the weather deteriorates through the morning.",
          "From the <strong>Jeng La</strong>, marked with prayer flags, the view south takes in the <strong>Dhaulagiri</strong> massif — a first sight of the main Himalayan chain after two weeks behind it — with the Tarap valley opening below.",
          "The descent is long, dropping around 850 m over scree and then onto grass as the valley broadens. The change is welcome: after the severity of northern Dolpo, the Tarap is green by comparison, with grazing land and cultivation.",
          "<strong>Tokyu Gaon (4,240 m)</strong> is a village with an old gompa at the head of the valley. Around 6 hours. Overnight camping at Tokyu Gaon.",
        ),
      },
      {
        index: 17,
        title: "Trek from Tokyu Gaon (4,240 m) to Dho Tarap (4,090 m)",
        html: p(
          "A short and easy day down the broad Tarap valley.",
          "The walking is gentle, losing only around 150 m along a wide, flat-bottomed valley — a striking contrast to the passes and gorges of the past fortnight. The <strong>Tarap</strong> is one of the highest inhabited valleys in the world, and the scale of it, ringed by bare mountains with a river winding through grazing land, is impressive.",
          "The route passes barley fields irrigated by channels, grazing yaks, and a succession of chortens and long mani walls.",
          "<strong>Dho Tarap (4,090 m)</strong> is the main settlement of the valley, a substantial village of flat-roofed mud and stone houses. Like much of Dolpo it has both <strong>Buddhist and Bön</strong> communities living side by side, with monasteries of each tradition nearby — an unusual arrangement that has persisted for centuries.",
          "The short day leaves the afternoon free to walk around the village. Around 3–4 hours. Overnight camping at Dho Tarap.",
        ),
      },
      {
        index: 18,
        title: "Acclimatization Day at Dho Tarap (4,090 m)",
        html: p(
          "A rest day in the Tarap valley — and, with the passes behind you, a genuinely relaxed one.",
          "The high crossings are done, so today is about recovery and about the place itself rather than preparation for what comes next.",
          "<strong>Dho Tarap</strong> rewards time. The <strong>Bön</strong> gompa at Shipchhok and the Buddhist <strong>Ribo Bhumpa</strong> are both within walking distance, and seeing the two traditions operating in the same small community is one of the more interesting things about Dolpo. Bön practitioners circumambulate anticlockwise; Buddhists clockwise.",
          "The villagers are of Tibetan origin, herding yaks and growing barley at an altitude where almost nothing else will grow, and the houses — flat-roofed, mud-walled, with fodder and firewood stacked on top — are built for extreme cold and wind.",
          "A gentle walk on the hillsides above the valley gives a good overview. Overnight camping at Dho Tarap.",
        ),
      },
      {
        index: 19,
        title: "Trek from Dho Tarap (4,090 m) to Tarap Khola (3,800 m)",
        html: p(
          "The start of the long descent south, following the Tarap Khola out of the high valley.",
          "The trail leaves Dho Tarap and heads down the valley, losing around 290 m. The going is easy at first across the open valley floor, but the country begins to close in as the river cuts down.",
          "By the afternoon the broad Tarap valley has narrowed into the head of a gorge, and the trail starts traversing above the water rather than beside it. The vegetation, absent for so long, starts to return — juniper, scrub and the first stunted trees.",
          "This section is used by yak and mule caravans moving between Tarap and the lower valleys, and you are likely to meet them; the trail is narrow in places and it is normal to stand aside on the uphill side while animals pass.",
          "Camp is beside the <strong>Tarap Khola (3,800 m)</strong>. Around 5 hours. Overnight camping at Tarap Khola.",
        ),
      },
      {
        index: 20,
        title: "Trek from Tarap Khola (3,800 m) to Khanigaun (2,550 m)",
        html: p(
          "A long descent of 1,250 m through the spectacular Tarap gorge.",
          "This is one of the most dramatic days of the trek. The trail follows the <strong>Tarap Khola</strong> down through a deep, narrow gorge with sheer rock walls, and the path is cut into the cliff face, crossing and recrossing the river on wooden and suspension bridges.",
          "Some sections are exposed and require care, and the trail is rough underfoot throughout. It is old trading-route engineering, maintained by the villages, and in places it is carried on wooden galleries pinned to the rock.",
          "The descent brings a rapid change of environment. Over the course of the day you drop through juniper into birch, pine and eventually mixed broadleaf forest, and the air becomes noticeably warmer and thicker after weeks above 3,800 m.",
          "<strong>Khanigaun (2,550 m)</strong> is a village in the lower valley with terraced fields around it. Around 6–7 hours. Overnight camping at Khanigaun.",
        ),
      },
      {
        index: 21,
        title: "Trek from Khanigaun (2,550 m) to Tarakot (2,543 m)",
        html: p(
          "An easy day along the valley with essentially no net height change.",
          "The trail continues down the river through increasingly green and populated country. After the severity of the north, this is comfortable walking — terraced fields of barley, buckwheat and millet, walnut and apricot trees, and villages at regular intervals.",
          "The cultural shift is as marked as the change in vegetation. The upper valleys were entirely Tibetan; here the villages are Nepali-speaking and partly Hindu, and the architecture, dress and farming are all different. Walking out of Dolpo makes the contrast between its two halves very clear.",
          "<strong>Tarakot (2,543 m)</strong> was historically the fortified capital of this region, and the old fort site — known locally as Dzong — sits on a hill above the village, with a gompa nearby. It was an important stop on the trading route between Tibet and the Nepali lowlands.",
          "Around 4–5 hours. Overnight camping at Tarakot.",
        ),
      },
      {
        index: 22,
        title: "Trek from Tarakot (2,543 m) to Dunai (2,140 m)",
        html: p(
          "A gentle descent of around 400 m back to the district headquarters, closing the loop.",
          "The trail rejoins the <strong>Thuli Bheri</strong> and follows it downstream on a well-used path, crossing suspension bridges and traversing hillsides above the water. The walking is easy and the day relatively short.",
          "This is familiar ground — you passed through here on the second day of walking, more than three weeks ago, heading in the opposite direction. Coming back to it after the Kang La, Shey Gompa, Saldang and the Tarap gorge gives a good sense of the scale of the circuit just completed.",
          "The country is green and farmed, with pine on the slopes and terraces along the river, and the altitude of just over 2,000 m feels positively luxurious.",
          "<strong>Dunai (2,140 m)</strong> has shops, a hospital and, after weeks of camping, the novelty of a proper town.",
          "Around 4–5 hours. Overnight camping at Dunai.",
        ),
      },
      {
        index: 23,
        title: "Trek from Dunai (2,140 m) to Juphal (2,320 m)",
        html: p(
          "The final walking day of the trek, a short climb back to the airstrip.",
          "The trail follows the <strong>Thuli Bheri</strong> briefly before climbing around 180 m through terraced fields and pine forest to Juphal. It is a straightforward couple of hours and an easy way to finish.",
          "There are last views back up the valleys toward the mountains, and a final walk through the farming villages of the lower district — walnut trees, irrigation channels, grain drying on rooftops.",
          "<strong>Juphal (2,320 m)</strong> is where the trek ends. This is the point to settle up with the camping crew, the cook and the animal handlers, many of whom will have been with you for over three weeks and will now head back to their own villages. A tip and a proper thank-you are customary and well earned.",
          "Flights out are entirely weather-dependent, so an early night is sensible. Around 3 hours. Overnight in Juphal.",
        ),
      },
      {
        index: 24,
        title: "Fly from Juphal (2,320 m) to Nepalgunj (150 m) and Fly to Kathmandu (1,400 m)",
        html: p(
          "Two flights in one day, returning from Dolpo to the capital.",
          "The morning flight from <strong>Juphal</strong> leaves early, before the wind picks up, and gives a final aerial view of the Dolpo ranges and the Dhaulagiri massif — a chance to see the whole geography of the trek at once, including the pass country you crossed on foot.",
          "It bears repeating that this flight is weather-dependent, and delays of a day or more are normal in Dolpo. A buffer day at the end of any trip here is strongly advisable.",
          "At <strong>Nepalgunj (150 m)</strong> you connect to the onward flight to Kathmandu, dropping into the heat of the Terai before climbing back to the valley.",
          "You arrive in <strong>Kathmandu (1,400 m)</strong> and transfer to your hotel. After more than three weeks of camping, the shower, the bed and the meal are all memorable. The evening is free. Overnight in Kathmandu.",
        ),
      },
      {
        index: 25,
        title: "Departure from Kathmandu (1,400 m)",
        html: p(
          "The final day of the <strong>Upper Dolpo Trek</strong>.",
          "Depending on your flight time there may be free hours in the morning. Thamel is the obvious place for last-minute shopping, and if you have half a day, <strong>Boudhanath</strong> and <strong>Swayambhunath</strong> connect to the Tibetan Buddhist culture you have just travelled through — though the Bön monasteries of Shey, Yangze and Dho Tarap belong to an older tradition still.",
          "Our representative collects you from your hotel and transfers you to <strong>Tribhuvan International Airport</strong> around three hours before departure.",
          "You leave having completed one of the longest and most remote treks in Nepal: over the <strong>Kang La (5,360 m)</strong>, <strong>Saldang La (5,010 m)</strong> and <strong>Jeng La (5,090 m)</strong>, to <strong>Shey Gompa</strong> beneath the sacred Crystal Mountain, through Saldang and the Tarap valley — a journey through country where Tibetan Buddhist and Bön traditions have continued almost untouched.",
        ),
      },
    ],
  },
];
